In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [4]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  ...    Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
0          1    15634602  Hargrave          619    France  Female  ...       0.00              1          1               1        101348.88       1
1          2    15647311      Hill          608     Spain  Female  ...   83807.86              1          0               1        112542.58       0
2          3    15619304      Onio          502    France  Female  ...  159660.80              3          1               0        113931.57       1
3          4    15701354      Boni          699    France  Female  ...       0.00              2          0               0         93826.63       0
4          5    15737888  Mitchell          850     Spain  Female  ...  125510.82              1          1               1         79084.10       0

[5 rows x 14 columns]

#### Pre Process the data

In [5]:
data.drop(["RowNumber", "CustomerId", "Surname"] , axis=1, inplace=True)

#### Label Encode Categorical Features`

In [6]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

#### One Hot Geography

In [7]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

#### Combine one hot encoded with original data

In [8]:
data = pd.concat([data.drop("Geography", axis=1), geo_encoded_df], axis=1)
data.head()

   CreditScore  Gender  Age  Tenure    Balance  ...  EstimatedSalary  Exited  Geography_France  Geography_Germany  Geography_Spain
0          619       0   42       2       0.00  ...        101348.88       1               1.0                0.0              0.0
1          608       0   41       1   83807.86  ...        112542.58       0               0.0                0.0              1.0
2          502       0   42       8  159660.80  ...        113931.57       1               1.0                0.0              0.0
3          699       0   39       1       0.00  ...         93826.63       0               1.0                0.0              0.0
4          850       0   43       2  125510.82  ...         79084.10       0               0.0                0.0              1.0

[5 rows x 13 columns]

#### Split into features and target

In [9]:
X = data.drop("EstimatedSalary", axis=1)
y = data["EstimatedSalary"]

In [25]:
X.shape
y.shape

(10000,)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#### Apply Standard Scalar

In [27]:
scaler = StandardScaler()
X_train  = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

#### Save Pickle Files

In [28]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [35]:
# X_train.shape
# X_test.shape
# y_train.shape

#### Train with Regression Problem Statement

In [14]:
import tensorflow as tf
from tensorflow.keras import Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#### Build the model

In [36]:
model = Sequential([
    Input(shape=(X_train.shape[1],)),
    Dense(64, activation='relu'), # HL1 connected with input layer
    Dense(32, activation='relu'), ## HL2
    Dense(1) ## output layer, when we dont apply any activation function the default will be linear activation function
]
)

# Linear activation function is basically whatever output we are getting we are not doing anything
# to it we are just returning that

#### Compile the model

In [37]:
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                      │ (None, 64)                  │             832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

#set up tensorboard
log_dir = "regressionlogs/fit/"
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq = 1)

In [39]:
early_stopping_callback = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)

In [40]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs = 100,
    callbacks = [early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 100590.2031 - mae: 100590.2031 - val_loss: 98532.8047 - val_mae: 98532.8047
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 100543.7500 - mae: 100543.7500 - val_loss: 97139.2344 - val_mae: 97139.2344
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 98773.6250 - mae: 98773.6250 - val_loss: 93550.8984 - val_mae: 93550.8984
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 93152.0078 - mae: 93152.0078 - val_loss: 87503.3203 - val_mae: 87503.3203
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 87244.6562 - mae: 87244.6562 - val_loss: 79550.2891 - val_mae: 79550.2891
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 78485.6016 - mae: 78485.6016 - val_loss: 70956.4688 - val_mae: 70956.4688
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 70091.8750 - mae: 70091.8750 - val_loss: 63106.2344 - val_mae: 63106.2344
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 62611.3594 - mae: 62611.3594 - val_loss: 57185.7070 - val_mae: 57185.7070
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 56205.6406 - mae: 56205.6406 - val_loss: 53418.6094 - val_mae: 53418.6094
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 52896.1680 - mae: 52896.1680 - val_loss: 51560.8789 - val_mae: 51560.8789
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 51433.2461 - mae: 51433.2461 - val_loss: 50902.1172 - val_mae: 50902.1172
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50718.4961 - mae: 50718.4961 - val_loss: 50671.8320 - val_mae: 50671.8320
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50406.8516 - mae: 50406.8516 - val_loss: 50584.9375 - val_mae: 50584.9375
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50376.9844 - mae: 50376.9844 - val_loss: 50530.9297 - val_mae: 50530.9297
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50856.8242 - mae: 50856.8242 - val_loss: 50490.7305 - val_mae: 50490.7305
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50547.0781 - mae: 50547.0781 - val_loss: 50450.5742 - val_mae: 50450.5742
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50379.3008 - mae: 50379.3008 - val_loss: 50416.3594 - val_mae: 50416.3594
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50002.2852 - mae: 50002.2852 - val_loss: 50393.6328 - val_mae: 50393.6328
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50231.9414 - mae: 50231.9414 - val_loss: 50366.4492 - val_mae: 50366.4492
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49878.9570 - mae: 49878.9570 - val_loss: 50337.8164 - val_mae: 50337.8164
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49914.6719 - mae: 49914.6719 - val_loss: 50319.5586 - val_mae: 50319.5586
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49871.1914 - mae: 49871.1914 - val_loss: 50305.3125 - val_mae: 50305.3125
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49237.0195 - mae: 49237.0195 - val_loss: 50278.9883 - val_mae: 50278.9883
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49656.0234 - mae: 49656.0234 - val_loss: 50271.2227 - val_mae: 50271.2227
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50067.9805 - mae: 50067.9805 - val_loss: 50263.3906 - val_mae: 50263.3906
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49740.1953 - mae: 49740.1953 - val_loss: 50239.7891 - val_mae: 50239.7891
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49326.8438 - mae: 49326.8438 - val_loss: 50233.1094 - val_mae: 50233.1094
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49836.7891 - mae: 49836.7891 - val_loss: 50231.1602 - val_mae: 50231.1602
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50075.5664 - mae: 50075.5664 - val_loss: 50227.4688 - val_mae: 50227.4688
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50026.9023 - mae: 50026.9023 - val_loss: 50214.6719 - val_mae: 50214.6719
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49359.6562 - mae: 49359.6562 - val_loss: 50213.6797 - val_mae: 50213.6797
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49334.8320 - mae: 49334.8320 - val_loss: 50217.0156 - val_mae: 50217.0156
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49262.2539 - mae: 49262.2539 - val_loss: 50210.6875 - val_mae: 50210.6875
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49673.2383 - mae: 49673.2383 - val_loss: 50206.6445 - val_mae: 50206.6445
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50162.1406 - mae: 50162.1406 - val_loss: 50207.2031 - val_mae: 50207.2031
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49522.8594 - mae: 49522.8594 - val_loss: 50207.2617 - val_mae: 50207.2617
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49609.2344 - mae: 49609.2344 - val_loss: 50197.5977 - val_mae: 50197.5977
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49167.3750 - mae: 49167.3750 - val_loss: 50184.6719 - val_mae: 50184.6719
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49287.2344 - mae: 49287.2344 - val_loss: 50185.1836 - val_mae: 50185.1836
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49464.8594 - mae: 49464.8594 - val_loss: 50176.2031 - val_mae: 50176.2031
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49384.3086 - mae: 49384.3086 - val_loss: 50176.2031 - val_mae: 50176.2031
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50138.2656 - mae: 50138.2656 - val_loss: 50180.2148 - val_mae: 50180.2148
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49616.7188 - mae: 49616.7188 - val_loss: 50181.0586 - val_mae: 50181.0586
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49934.7266 - mae: 49934.7266 - val_loss: 50189.4844 - val_mae: 50189.4844
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 48883.0000 - mae: 48883.0000 - val_loss: 50188.7695 - val_mae: 50188.7695
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49226.1992 - mae: 49226.1992 - val_loss: 50184.4766 - val_mae: 50184.4766
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49604.5820 - mae: 49604.5820 - val_loss: 50184.9453 - val_mae: 50184.9453
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 48855.4883 - mae: 48855.4883 - val_loss: 50176.8008 - val_mae: 50176.8008
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49655.3438 - mae: 49655.3438 - val_loss: 50171.7383 - val_mae: 50171.7383
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49468.4414 - mae: 49468.4414 - val_loss: 50184.7539 - val_mae: 50184.7539
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49436.4609 - mae: 49436.4609 - val_loss: 50185.1758 - val_mae: 50185.1758
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49324.7812 - mae: 49324.7812 - val_loss: 50191.3867 - val_mae: 50191.3867
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49214.2656 - mae: 49214.2656 - val_loss: 50196.0938 - val_mae: 50196.0938
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49333.7344 - mae: 49333.7344 - val_loss: 50198.5586 - val_mae: 50198.5586
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49213.3398 - mae: 49213.3398 - val_loss: 50199.1328 - val_mae: 50199.1328
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49759.8867 - mae: 49759.8867 - val_loss: 50199.3008 - val_mae: 50199.3008
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49541.3359 - mae: 49541.3359 - val_loss: 50199.9609 - val_mae: 50199.9609
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49391.4531 - mae: 49391.4531 - val_loss: 50208.6914 - val_mae: 50208.6914
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49622.8242 - mae: 49622.8242 - val_loss: 50208.0000 - val_mae: 50208.0000

In [42]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [44]:
%tensorboard --logdir regressionlogs/fit

#### Evaluate on test data

In [45]:
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 51123.5234 - mae: 51123.5234
Test MAE: 50171.73828125

In [46]:
model.save("regression_model.keras")